"""initial_tables

Revision ID: 01074b85cc9b
Revises:
Create Date: 2025-04-15 01:44:08.958415

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "01074b85cc9b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "test_questions",
        sa.Column(
            "type",
            sa.Enum(
                "OPTIONS", "INPUT", "NOT_STATED", name="questiontype"
            ),
            server_default=sa.text("'NOT_STATED'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_questions", "type")
    # ### end Alembic commands ###
