"""Initial setup with name field

Revision ID: 1e1320a77c21
Revises: 99df65b28f96
Create Date: 2025-03-22 16:28:05.006761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e1320a77c21'
down_revision: Union[str, None] = '99df65b28f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testquestions', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'testquestions', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testquestions', type_='unique')
    op.drop_column('testquestions', 'name')
    # ### end Alembic commands ###
