"""update type datetime->date

Revision ID: 2c761782c7c3
Revises: 35de90705ad7
Create Date: 2025-04-16 13:01:59.146715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c761782c7c3"
down_revision: Union[str, None] = "35de90705ad7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_workouts",
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
    )
    op.add_column(
        "user_workouts",
        sa.Column("calories_burned", sa.Float(), nullable=False),
    )
    op.drop_column("workouts", "duration_minutes")
    op.drop_column("workouts", "calories_burned")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workouts",
        sa.Column(
            "calories_burned",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "workouts",
        sa.Column(
            "duration_minutes",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("user_workouts", "calories_burned")
    op.drop_column("user_workouts", "duration_minutes")
    # ### end Alembic commands ###
