"""Initial revision

Revision ID: 3c6e9d19ef85
Revises: 
Create Date: 2025-04-18 12:31:34.765221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c6e9d19ef85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('food_items_name_key', 'food_items', type_='unique')
    op.create_index(op.f('ix_food_items_name'), 'food_items', ['name'], unique=True)
    op.add_column('user_workouts', sa.Column('workout_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    op.add_column('user_workouts', sa.Column('duration_minutes', sa.Integer(), nullable=False))
    op.add_column('user_workouts', sa.Column('calories_burned', sa.Float(), nullable=False))
    op.create_index('ix_user_workouts_user_date', 'user_workouts', ['user_id', 'workout_date'], unique=False)
    op.create_index(op.f('ix_user_workouts_workout_date'), 'user_workouts', ['workout_date'], unique=False)
    op.drop_column('user_workouts', 'created_at')
    op.create_index(op.f('ix_workouts_name'), 'workouts', ['name'], unique=True)
    op.create_index('ix_workouts_name_description_trgm', 'workouts', ['name', 'description'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops', 'description': 'gin_trgm_ops'})
    op.create_index('ix_workouts_name_lower', 'workouts', [sa.literal_column('lower(name)')], unique=False, postgresql_using='btree')
    op.create_index('ix_workouts_name_trgm', 'workouts', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_column('workouts', 'duration_minutes')
    op.drop_column('workouts', 'calories_burned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('calories_burned', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('workouts', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('ix_workouts_name_trgm', table_name='workouts', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_workouts_name_lower', table_name='workouts', postgresql_using='btree')
    op.drop_index('ix_workouts_name_description_trgm', table_name='workouts', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops', 'description': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_workouts_name'), table_name='workouts')
    op.add_column('user_workouts', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_workouts_workout_date'), table_name='user_workouts')
    op.drop_index('ix_user_workouts_user_date', table_name='user_workouts')
    op.drop_column('user_workouts', 'calories_burned')
    op.drop_column('user_workouts', 'duration_minutes')
    op.drop_column('user_workouts', 'workout_date')
    op.drop_index(op.f('ix_food_items_name'), table_name='food_items')
    op.create_unique_constraint('food_items_name_key', 'food_items', ['name'])
    # ### end Alembic commands ###
