"""update name in testque

Revision ID: 93a6360a5473
Revises: 1e1320a77c21
Create Date: 2025-03-22 19:09:46.957604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a6360a5473'
down_revision: Union[str, None] = '1e1320a77c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('testquestions_name_key', 'testquestions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('testquestions_name_key', 'testquestions', ['name'])
    # ### end Alembic commands ###
