"""lazyjoin deleted(по умолчанию)

Revision ID: 99df65b28f96
Revises: 8b50e93a9221
Create Date: 2025-03-21 23:20:54.554204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99df65b28f96'
down_revision: Union[str, None] = '8b50e93a9221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
