"""+связи в еде

Revision ID: bdced3c48fcd
Revises: 8d2d6fe8a318
Create Date: 2025-03-13 20:05:40.630166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdced3c48fcd'
down_revision: Union[str, None] = '8d2d6fe8a318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
