"""add index workouts for search str

Revision ID: c8c07641378d
Revises: 2c761782c7c3
Create Date: 2025-04-16 14:37:50.250863

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c8c07641378d"
down_revision: Union[str, None] = "2c761782c7c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "food_items_name_key", "food_items", type_="unique"
    )
    op.create_index(
        op.f("ix_food_items_name"),
        "food_items",
        ["name"],
        unique=True,
    )
    op.create_index(
        "ix_user_workouts_user_date",
        "user_workouts",
        ["user_id", "workout_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_workouts_workout_date"),
        "user_workouts",
        ["workout_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workouts_name"), "workouts", ["name"], unique=True
    )
    op.create_index(
        "ix_workouts_name_description_trgm",
        "workouts",
        ["name", "description"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={
            "name": "gin_trgm_ops",
            "description": "gin_trgm_ops",
        },
    )
    op.create_index(
        "ix_workouts_name_lower",
        "workouts",
        [sa.text("lower(name)")],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index(
        "ix_workouts_name_trgm",
        "workouts",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_workouts_name_trgm",
        table_name="workouts",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_workouts_name_lower",
        table_name="workouts",
        postgresql_using="btree",
    )
    op.drop_index(
        "ix_workouts_name_description_trgm",
        table_name="workouts",
        postgresql_using="gin",
        postgresql_ops={
            "name": "gin_trgm_ops",
            "description": "gin_trgm_ops",
        },
    )
    op.drop_index(op.f("ix_workouts_name"), table_name="workouts")
    op.drop_index(
        op.f("ix_user_workouts_workout_date"),
        table_name="user_workouts",
    )
    op.drop_index(
        "ix_user_workouts_user_date", table_name="user_workouts"
    )
    op.drop_index(
        op.f("ix_food_items_name"), table_name="food_items"
    )
    op.create_unique_constraint(
        "food_items_name_key", "food_items", ["name"]
    )
    # ### end Alembic commands ###
