"""update test relationships

Revision ID: e4a61101d2d5
Revises: c52138704c19
Create Date: 2025-03-20 23:59:49.055151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a61101d2d5'
down_revision: Union[str, None] = 'c52138704c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testresults', sa.Column('session_id', sa.String(length=128), nullable=False))
    op.add_column('testresults', sa.Column('birthday_date', sa.DateTime(), nullable=True))
    op.add_column('testresults', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('testresults', sa.Column('goal', sa.String(), nullable=True))
    op.add_column('testresults', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('testresults', sa.Column('weight', sa.Float(), nullable=True))
    op.create_index(op.f('ix_testresults_session_id'), 'testresults', ['session_id'], unique=False)
    op.drop_constraint('testresults_question_id_fkey', 'testresults', type_='foreignkey')
    op.drop_constraint('testresults_user_id_fkey', 'testresults', type_='foreignkey')
    op.drop_column('testresults', 'user_id')
    op.drop_column('testresults', 'answer')
    op.drop_column('testresults', 'question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testresults', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('testresults', sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('testresults', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('testresults_user_id_fkey', 'testresults', 'users', ['user_id'], ['id'])
    op.create_foreign_key('testresults_question_id_fkey', 'testresults', 'testquestions', ['question_id'], ['id'])
    op.drop_index(op.f('ix_testresults_session_id'), table_name='testresults')
    op.drop_column('testresults', 'weight')
    op.drop_column('testresults', 'height')
    op.drop_column('testresults', 'goal')
    op.drop_column('testresults', 'gender')
    op.drop_column('testresults', 'birthday_date')
    op.drop_column('testresults', 'session_id')
    # ### end Alembic commands ###
