"""update test relationships2

Revision ID: fe8ce5872332
Revises: e4a61101d2d5
Create Date: 2025-03-21 00:28:58.766052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8ce5872332'
down_revision: Union[str, None] = 'e4a61101d2d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testresults', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'testresults', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'testresults', type_='foreignkey')
    op.drop_column('testresults', 'user_id')
    # ### end Alembic commands ###
