"""Обновлена таблица goals

Revision ID: 721951d68127
Revises: 9e9e1f2ba0c8
Create Date: 2025-03-02 18:09:58.017635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721951d68127'
down_revision: Union[str, None] = '9e9e1f2ba0c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
