REAL_FOOD_ITEMS = [
    # Молочные продукты 
    {"name": "Творог 9%", "calories": 159, "proteins": 16, "fats": 9, "carbs": 3},
    {"name": "Йогурт греческий", "calories": 133, "proteins": 10, "fats": 5, "carbs": 9},
    {"name": "Сыр адыгейский", "calories": 264, "proteins": 19, "fats": 19, "carbs": 1.5},
    {"name": "Кефир 1%", "calories": 40, "proteins": 3.0, "fats": 1.0, "carbs": 4.0},
    {"name": "Сыр моцарелла", "calories": 280, "proteins": 28, "fats": 17, "carbs": 3.1},
    {"name": "Молоко топленое 4%", "calories": 67, "proteins": 3.0, "fats": 4.0, "carbs": 4.7},
    {"name": "Сыр чеддер", "calories": 402, "proteins": 25, "fats": 33, "carbs": 1.3},
    {"name": "Сливки 20%", "calories": 205, "proteins": 2.8, "fats": 20, "carbs": 3.7},
    {"name": "Йогурт натуральный 2%", "calories": 60, "proteins": 4.3, "fats": 2.0, "carbs": 6.2},
    {"name": "Творожный сыр", "calories": 342, "proteins": 6.0, "fats": 34, "carbs": 4.0},
    {"name": "Сыр пармезан", "calories": 392, "proteins": 35, "fats": 25, "carbs": 3.2},
    {"name": "Молоко безлактозное", "calories": 52, "proteins": 3.0, "fats": 2.5, "carbs": 4.8},
    {"name": "Сметана 20%", "calories": 206, "proteins": 2.8, "fats": 20, "carbs": 3.2},
    {"name": "Кумыс", "calories": 50, "proteins": 3.0, "fats": 1.9, "carbs": 5.0},
    {"name": "Сыр рикотта", "calories": 174, "proteins": 11, "fats": 13, "carbs": 3.0},
    {"name": "Молочная сыворотка", "calories": 27, "proteins": 0.8, "fats": 0.2, "carbs": 5.1},
    {"name": "Сыр камамбер", "calories": 300, "proteins": 20, "fats": 24, "carbs": 0.5},
    {"name": "Творог зерненый", "calories": 110, "proteins": 12, "fats": 5.0, "carbs": 3.0},
    {"name": "Сыр брынза", "calories": 262, "proteins": 22, "fats": 19, "carbs": 0.7},
    {"name": "Йогурт питьевой фруктовый", "calories": 85, "proteins": 2.8, "fats": 1.5, "carbs": 15},
    {"name": "Сыр эдам", "calories": 357, "proteins": 25, "fats": 27, "carbs": 1.4},
    {"name": "Молоко козье", "calories": 69, "proteins": 3.6, "fats": 4.1, "carbs": 4.5},
    {"name": "Сыр дор блю", "calories": 354, "proteins": 21, "fats": 30, "carbs": 2.3},
    {"name": "Творожок детский", "calories": 103, "proteins": 10, "fats": 5.5, "carbs": 4.0},
    {"name": "Сыр маасдам", "calories": 350, "proteins": 23, "fats": 26, "carbs": 2.0},
    {"name": "Кефир бифидок", "calories": 56, "proteins": 2.8, "fats": 2.5, "carbs": 5.0},
    {"name": "Сыр косичка", "calories": 320, "proteins": 25, "fats": 24, "carbs": 0},
    {"name": "Молоко сухое", "calories": 469, "proteins": 24, "fats": 25, "carbs": 39},
    {"name": "Сыр тофу", "calories": 76, "proteins": 8.1, "fats": 4.8, "carbs": 1.9},
    {"name": "Сыр филадельфия", "calories": 342, "proteins": 6.0, "fats": 34, "carbs": 4.0},

    # Мясо и птица 
    {"name": "Говядина лопатка", "calories": 137, "proteins": 19, "fats": 6.0, "carbs": 0},
    {"name": "Куриные окорочка", "calories": 158, "proteins": 18, "fats": 9.0, "carbs": 0},
    {"name": "Свиная вырезка", "calories": 142, "proteins": 19, "fats": 7.0, "carbs": 0},
    {"name": "Баранина", "calories": 209, "proteins": 17, "fats": 16, "carbs": 0},
    {"name": "Куриный фарш", "calories": 143, "proteins": 17, "fats": 8.0, "carbs": 0},
    {"name": "Говяжий фарш", "calories": 254, "proteins": 17, "fats": 20, "carbs": 0},
    {"name": "Свиная грудинка", "calories": 518, "proteins": 9.3, "fats": 53, "carbs": 0},
    {"name": "Колбаса Краковская", "calories": 466, "proteins": 16, "fats": 45, "carbs": 0},
    {"name": "Куриные желудки", "calories": 114, "proteins": 18, "fats": 4.0, "carbs": 0},
    {"name": "Говяжьи ребра", "calories": 233, "proteins": 17, "fats": 19, "carbs": 0},
    {"name": "Колбаса Чоризо", "calories": 455, "proteins": 24, "fats": 38, "carbs": 1.9},
    {"name": "Куриное филе", "calories": 110, "proteins": 23, "fats": 1.2, "carbs": 0},
    {"name": "Свиная корейка", "calories": 267, "proteins": 16, "fats": 22, "carbs": 0},
    {"name": "Говяжья грудинка", "calories": 217, "proteins": 19, "fats": 15, "carbs": 0},
    {"name": "Колбаса Брауншвейгская", "calories": 463, "proteins": 16, "fats": 44, "carbs": 0},
    {"name": "Утиная грудка", "calories": 159, "proteins": 19, "fats": 9.0, "carbs": 0},
    {"name": "Свиные уши", "calories": 234, "proteins": 21, "fats": 16, "carbs": 0},
    {"name": "Говяжьи хвосты", "calories": 181, "proteins": 19, "fats": 11, "carbs": 0},
    {"name": "Колбаса Венская", "calories": 311, "proteins": 12, "fats": 29, "carbs": 1.0},
    {"name": "Куриные шеи", "calories": 297, "proteins": 14, "fats": 26, "carbs": 0},
    {"name": "Свиная рулька", "calories": 294, "proteins": 16, "fats": 25, "carbs": 0},
    {"name": "Говяжьи мозги", "calories": 143, "proteins": 11, "fats": 10, "carbs": 1.0},
    {"name": "Колбаса Московская", "calories": 463, "proteins": 16, "fats": 44, "carbs": 0},
    {"name": "Перепелка", "calories": 192, "proteins": 20, "fats": 12, "carbs": 0},
    {"name": "Свиные ребра", "calories": 277, "proteins": 15, "fats": 24, "carbs": 0},
    {"name": "Говяжьи почки", "calories": 86, "proteins": 15, "fats": 3.0, "carbs": 1.0},
    {"name": "Колбаса Охотничья", "calories": 463, "proteins": 16, "fats": 44, "carbs": 0},
    {"name": "Цыпленок", "calories": 170, "proteins": 18, "fats": 11, "carbs": 0},
    {"name": "Свиная печень", "calories": 130, "proteins": 21, "fats": 4.0, "carbs": 3.0},
    {"name": "Говяжье сердце", "calories": 112, "proteins": 17, "fats": 5.0, "carbs": 0},

    # Рыба и морепродукты 
    {"name": "Семга слабосоленая", "calories": 202, "proteins": 22, "fats": 12, "carbs": 0},
    {"name": "Кета", "calories": 127, "proteins": 20, "fats": 5.6, "carbs": 0},
    {"name": "Омар", "calories": 90, "proteins": 19, "fats": 1.0, "carbs": 0.5},
    {"name": "Сельдь свежая", "calories": 158, "proteins": 18, "fats": 9.0, "carbs": 0},
    {"name": "Камбала", "calories": 83, "proteins": 16, "fats": 1.5, "carbs": 0},
    {"name": "Морской окунь", "calories": 79, "proteins": 16, "fats": 1.0, "carbs": 0},
    {"name": "Сом", "calories": 95, "proteins": 16, "fats": 3.0, "carbs": 0},
    {"name": "Тунец свежий", "calories": 144, "proteins": 23, "fats": 5.0, "carbs": 0},
    {"name": "Угорь", "calories": 236, "proteins": 18, "fats": 18, "carbs": 0},
    {"name": "Хек", "calories": 86, "proteins": 16, "fats": 2.2, "carbs": 0},
    {"name": "Щука", "calories": 84, "proteins": 18, "fats": 1.0, "carbs": 0},
    {"name": "Сазан", "calories": 97, "proteins": 18, "fats": 2.0, "carbs": 0},
    {"name": "Стерлядь", "calories": 88, "proteins": 17, "fats": 2.0, "carbs": 0},
    {"name": "Форель радужная", "calories": 119, "proteins": 20, "fats": 3.8, "carbs": 0},
    {"name": "Судак", "calories": 84, "proteins": 18, "fats": 1.1, "carbs": 0},
    {"name": "Треска печень", "calories": 613, "proteins": 4.2, "fats": 65, "carbs": 0},
    {"name": "Карась", "calories": 87, "proteins": 18, "fats": 1.8, "carbs": 0},
    {"name": "Лещ", "calories": 105, "proteins": 17, "fats": 4.4, "carbs": 0},
    {"name": "Севрюга", "calories": 160, "proteins": 16, "fats": 10, "carbs": 0},
    {"name": "Белуга", "calories": 147, "proteins": 16, "fats": 9.0, "carbs": 0},

    # Овощи и зелень 
    {"name": "Авокадо", "calories": 160, "proteins": 2.0, "fats": 15, "carbs": 9.0},
    {"name": "Артишок", "calories": 47, "proteins": 3.3, "fats": 0.2, "carbs": 11},
    {"name": "Базилик", "calories": 23, "proteins": 3.2, "fats": 0.6, "carbs": 2.7},
    {"name": "Брюква", "calories": 37, "proteins": 1.2, "fats": 0.2, "carbs": 8.0},
    {"name": "Дайкон", "calories": 18, "proteins": 0.6, "fats": 0.1, "carbs": 4.1},
    {"name": "Имбирь", "calories": 80, "proteins": 1.8, "fats": 0.8, "carbs": 18},
    {"name": "Капуста брюссельская", "calories": 43, "proteins": 3.4, "fats": 0.3, "carbs": 9.0},
    {"name": "Капуста краснокочанная", "calories": 31, "proteins": 1.4, "fats": 0.2, "carbs": 7.0},
    {"name": "Капуста пекинская", "calories": 16, "proteins": 1.2, "fats": 0.2, "carbs": 3.2},
    {"name": "Кольраби", "calories": 27, "proteins": 1.7, "fats": 0.1, "carbs": 6.2},
    {"name": "Кресс-салат", "calories": 32, "proteins": 2.6, "fats": 0.7, "carbs": 5.5},
    {"name": "Лук-порей", "calories": 61, "proteins": 1.5, "fats": 0.3, "carbs": 14},
    {"name": "Лук-шалот", "calories": 72, "proteins": 2.5, "fats": 0.1, "carbs": 17},
    {"name": "Мангольд", "calories": 19, "proteins": 1.8, "fats": 0.2, "carbs": 3.7},
    {"name": "Морская капуста", "calories": 49, "proteins": 0.9, "fats": 0.2, "carbs": 12},
    {"name": "Пастернак", "calories": 75, "proteins": 1.2, "fats": 0.3, "carbs": 18},
    {"name": "Патиссон", "calories": 19, "proteins": 0.6, "fats": 0.1, "carbs": 4.0},
    {"name": "Перец чили", "calories": 40, "proteins": 2.0, "fats": 0.2, "carbs": 9.0},
    {"name": "Редька черная", "calories": 36, "proteins": 1.9, "fats": 0.2, "carbs": 8.0},
    {"name": "Репа", "calories": 32, "proteins": 1.5, "fats": 0.1, "carbs": 7.0},
    {"name": "Руккола", "calories": 25, "proteins": 2.6, "fats": 0.7, "carbs": 3.7},
    {"name": "Салат айсберг", "calories": 14, "proteins": 0.9, "fats": 0.1, "carbs": 3.0},
    {"name": "Салат корн", "calories": 21, "proteins": 1.8, "fats": 0.4, "carbs": 3.6},
    {"name": "Салат латук", "calories": 15, "proteins": 1.4, "fats": 0.2, "carbs": 2.9},
    {"name": "Сельдерей корневой", "calories": 42, "proteins": 1.5, "fats": 0.3, "carbs": 9.2},
    {"name": "Сельдерей стеблевой", "calories": 16, "proteins": 0.7, "fats": 0.2, "carbs": 3.0},
    {"name": "Спаржа", "calories": 20, "proteins": 2.2, "fats": 0.1, "carbs": 3.9},
    {"name": "Топинамбур", "calories": 61, "proteins": 2.0, "fats": 0.1, "carbs": 13},
    {"name": "Фенхель", "calories": 31, "proteins": 1.2, "fats": 0.2, "carbs": 7.3},
    {"name": "Цуккини", "calories": 17, "proteins": 1.2, "fats": 0.3, "carbs": 3.1},

    # Фрукты и ягоды 
    {"name": "Абрикос", "calories": 48, "proteins": 1.4, "fats": 0.4, "carbs": 11},
    {"name": "Айва", "calories": 57, "proteins": 0.4, "fats": 0.1, "carbs": 15},
    {"name": "Алыча", "calories": 46, "proteins": 0.2, "fats": 0.1, "carbs": 11},
    {"name": "Барбарис", "calories": 29, "proteins": 0.0, "fats": 0.0, "carbs": 7.0},
    {"name": "Боярышник", "calories": 52, "proteins": 0.0, "fats": 0.0, "carbs": 14},
    {"name": "Бузина", "calories": 73, "proteins": 0.7, "fats": 0.5, "carbs": 18},
    {"name": "Вишня", "calories": 52, "proteins": 0.8, "fats": 0.2, "carbs": 12},
    {"name": "Голубика", "calories": 57, "proteins": 0.7, "fats": 0.3, "carbs": 14},
    {"name": "Ежевика", "calories": 43, "proteins": 1.4, "fats": 0.5, "carbs": 10},
    {"name": "Жимолость", "calories": 41, "proteins": 0.0, "fats": 0.0, "carbs": 10},
    {"name": "Земляника", "calories": 41, "proteins": 0.8, "fats": 0.4, "carbs": 8.0},
    {"name": "Инжир", "calories": 74, "proteins": 0.8, "fats": 0.3, "carbs": 19},
    {"name": "Кизил", "calories": 40, "proteins": 1.0, "fats": 0.0, "carbs": 10},
    {"name": "Кумкват", "calories": 71, "proteins": 1.9, "fats": 0.9, "carbs": 16},
    {"name": "Лайм", "calories": 30, "proteins": 0.7, "fats": 0.2, "carbs": 11},
    {"name": "Лимон", "calories": 29, "proteins": 1.1, "fats": 0.3, "carbs": 9.0},
    {"name": "Маракуйя", "calories": 97, "proteins": 2.2, "fats": 0.7, "carbs": 23},
    {"name": "Облепиха", "calories": 82, "proteins": 1.2, "fats": 5.4, "carbs": 10},
    {"name": "Папайя", "calories": 43, "proteins": 0.5, "fats": 0.3, "carbs": 11},
    {"name": "Помело", "calories": 38, "proteins": 0.8, "fats": 0.0, "carbs": 10},
    {"name": "Рябина красная", "calories": 50, "proteins": 1.4, "fats": 0.2, "carbs": 11},
    {"name": "Фейхоа", "calories": 49, "proteins": 1.0, "fats": 0.8, "carbs": 11},
    {"name": "Хурма", "calories": 67, "proteins": 0.5, "fats": 0.4, "carbs": 18},
    {"name": "Черешня", "calories": 50, "proteins": 1.1, "fats": 0.2, "carbs": 12},
    {"name": "Шелковица", "calories": 43, "proteins": 1.4, "fats": 0.4, "carbs": 10},
    {"name": "Яблоко Гренни Смит", "calories": 52, "proteins": 0.3, "fats": 0.2, "carbs": 14},
    {"name": "Яблоко Ред Делишес", "calories": 52, "proteins": 0.3, "fats": 0.2, "carbs": 14},
    {"name": "Яблоко Фуджи", "calories": 52, "proteins": 0.3, "fats": 0.2, "carbs": 14},
    {"name": "Яблоко Антоновка", "calories": 47, "proteins": 0.4, "fats": 0.4, "carbs": 12},
    {"name": "Яблоко Симиренко", "calories": 52, "proteins": 0.3, "fats": 0.2, "carbs": 14},

    # Крупы, макароны, бобовые 
    {"name": "Манная крупа", "calories": 328, "proteins": 10, "fats": 1.0, "carbs": 74},
    {"name": "Полба", "calories": 337, "proteins": 15, "fats": 2.4, "carbs": 70},
    {"name": "Ячменная крупа", "calories": 354, "proteins": 10, "fats": 2.3, "carbs": 78},
    {"name": "Рис коричневый", "calories": 337, "proteins": 7.0, "fats": 2.0, "carbs": 73},
    {"name": "Рис дикий", "calories": 357, "proteins": 15, "fats": 1.1, "carbs": 75},
    {"name": "Рис басмати", "calories": 340, "proteins": 7.5, "fats": 1.0, "carbs": 75},
    {"name": "Гречневая мука", "calories": 353, "proteins": 13, "fats": 3.4, "carbs": 72},
    {"name": "Кукурузная мука", "calories": 364, "proteins": 7.0, "fats": 3.9, "carbs": 76},
    {"name": "Маш", "calories": 300, "proteins": 24, "fats": 1.0, "carbs": 63},
    {"name": "Соя", "calories": 381, "proteins": 36, "fats": 20, "carbs": 30},

    # Хлеб и выпечка 
    {"name": "Хлеб ржаной", "calories": 259, "proteins": 9.0, "fats": 3.0, "carbs": 48},
    {"name": "Хлеб пшеничный", "calories": 265, "proteins": 7.6, "fats": 3.2, "carbs": 53},
    {"name": "Хлеб с отрубями", "calories": 227, "proteins": 7.5, "fats": 1.3, "carbs": 45},
    {"name": "Хлеб бездрожжевой", "calories": 210, "proteins": 6.5, "fats": 1.0, "carbs": 43},
    {"name": "Хлеб кукурузный", "calories": 266, "proteins": 6.7, "fats": 7.1, "carbs": 43},

    # Напитки 
    {"name": "Чай черный", "calories": 0, "proteins": 0, "fats": 0, "carbs": 0},
    {"name": "Кофе зерновой", "calories": 0, "proteins": 0, "fats": 0, "carbs": 0},
    {"name": "Какао", "calories": 374, "proteins": 24, "fats": 18, "carbs": 31},
    {"name": "Компот из сухофруктов", "calories": 60, "proteins": 0.5, "fats": 0, "carbs": 15},
    {"name": "Кисель", "calories": 53, "proteins": 0.2, "fats": 0, "carbs": 13},
    {"name": "Смузи фруктовый", "calories": 80, "proteins": 1.5, "fats": 0.5, "carbs": 18},
    {"name": "Молочный коктейль", "calories": 150, "proteins": 4.0, "fats": 5.0, "carbs": 22},
    {"name": "Горячий шоколад", "calories": 380, "proteins": 8.0, "fats": 17, "carbs": 50},
    {"name": "Чай каркаде", "calories": 5, "proteins": 0.3, "fats": 0, "carbs": 1.0},
    {"name": "Отвар шиповника", "calories": 19, "proteins": 0.6, "fats": 0, "carbs": 5.0},

    # Сладости и снеки 
    {"name": "Печенье овсяное", "calories": 437, "proteins": 6.5, "fats": 14, "carbs": 71},
    {"name": "Пряники", "calories": 350, "proteins": 5.0, "fats": 7.0, "carbs": 72},
    {"name": "Кекс", "calories": 339, "proteins": 5.0, "fats": 10, "carbs": 58},
    {"name": "Рулет с маком", "calories": 372, "proteins": 6.0, "fats": 12, "carbs": 60},
    {"name": "Шоколад горький", "calories": 539, "proteins": 6.2, "fats": 31, "carbs": 61},
    {"name": "Шоколад белый", "calories": 541, "proteins": 4.3, "fats": 32, "carbs": 59},
    {"name": "Конфеты карамель", "calories": 382, "proteins": 0, "fats": 0.2, "carbs": 96},
    {"name": "Конфеты шоколадные", "calories": 535, "proteins": 5.0, "fats": 29, "carbs": 63},
    {"name": "Пастила", "calories": 324, "proteins": 0.5, "fats": 0, "carbs": 80},
    {"name": "Щербет", "calories": 417, "proteins": 7.3, "fats": 15, "carbs": 66},
    {"name": "Халва тахинная", "calories": 516, "proteins": 13, "fats": 30, "carbs": 54},
    {"name": "Козинаки", "calories": 528, "proteins": 12, "fats": 28, "carbs": 55},
    {"name": "Гематоген", "calories": 354, "proteins": 6.0, "fats": 3.0, "carbs": 76},
    {"name": "Батончик мюсли", "calories": 420, "proteins": 8.0, "fats": 12, "carbs": 70},
    {"name": "Попкорн карамельный", "calories": 401, "proteins": 4.0, "fats": 12, "carbs": 72},
    {"name": "Сухофрукты ассорти", "calories": 359, "proteins": 3.0, "fats": 0.5, "carbs": 89},
    {"name": "Цукаты", "calories": 216, "proteins": 0.6, "fats": 0.2, "carbs": 55},
    {"name": "Орехи в шоколаде", "calories": 518, "proteins": 8.0, "fats": 32, "carbs": 52},
    {"name": "Печенье песочное", "calories": 458, "proteins": 5.0, "fats": 19, "carbs": 66},
    {"name": "Пирожное эклер", "calories": 262, "proteins": 4.0, "fats": 14, "carbs": 31},

    # Готовые блюда и полуфабрикаты 
    {"name": "Пельмени Сибирские", "calories": 275, "proteins": 12, "fats": 15, "carbs": 25},
    {"name": "Вареники с картошкой", "calories": 148, "proteins": 4.0, "fats": 3.5, "carbs": 26},
    {"name": "Блины с мясом", "calories": 265, "proteins": 12, "fats": 15, "carbs": 22},
    {"name": "Котлеты куриные", "calories": 267, "proteins": 18, "fats": 20, "carbs": 4.0},
    {"name": "Голубцы", "calories": 143, "proteins": 7.0, "fats": 5.0, "carbs": 18},
    {"name": "Оладьи", "calories": 233, "proteins": 6.1, "fats": 5.8, "carbs": 40},
    {"name": "Сырники", "calories": 183, "proteins": 18, "fats": 6.0, "carbs": 16},
    {"name": "Запеканка творожная", "calories": 168, "proteins": 14, "fats": 8.0, "carbs": 12},
    {"name": "Пицца Маргарита", "calories": 209, "proteins": 8.0, "fats": 6.0, "carbs": 30},
    {"name": "Лазанья", "calories": 132, "proteins": 7.0, "fats": 5.0, "carbs": 15},
    {"name": "Равиоли", "calories": 203, "proteins": 8.0, "fats": 7.0, "carbs": 28},
    {"name": "Манты", "calories": 220, "proteins": 10, "fats": 12, "carbs": 20},
    {"name": "Хинкали", "calories": 159, "proteins": 10, "fats": 5.0, "carbs": 20},
    {"name": "Чебуреки", "calories": 296, "proteins": 8.0, "fats": 15, "carbs": 33},
    {"name": "Самса с мясом", "calories": 340, "proteins": 10, "fats": 20, "carbs": 30},
    {"name": "Курица гриль", "calories": 184, "proteins": 25, "fats": 8.0, "carbs": 0},
    {"name": "Шаурма", "calories": 290, "proteins": 12, "fats": 15, "carbs": 28},
    {"name": "Гамбургер", "calories": 295, "proteins": 12, "fats": 10, "carbs": 40},
    {"name": "Сэндвич с курицей", "calories": 250, "proteins": 14, "fats": 8.0, "carbs": 30},
    {"name": "Салат Цезарь", "calories": 350, "proteins": 15, "fats": 25, "carbs": 15},
    {"name": "Оливье", "calories": 198, "proteins": 5.0, "fats": 15, "carbs": 10},
    {"name": "Винегрет", "calories": 130, "proteins": 2.0, "fats": 10, "carbs": 10},
    {"name": "Борщ", "calories": 64, "proteins": 2.5, "fats": 3.0, "carbs": 7.0},
    {"name": "Щи", "calories": 50, "proteins": 2.0, "fats": 2.0, "carbs": 6.0},
    {"name": "Солянка", "calories": 95, "proteins": 5.0, "fats": 6.0, "carbs": 5.0},
    {"name": "Гречневая каша", "calories": 101, "proteins": 3.6, "fats": 2.2, "carbs": 18},
    {"name": "Овсяная каша", "calories": 88, "proteins": 3.0, "fats": 1.7, "carbs": 15},
    {"name": "Рисовая каша", "calories": 97, "proteins": 2.0, "fats": 0.5, "carbs": 22},
    {"name": "Манная каша", "calories": 120, "proteins": 3.0, "fats": 3.0, "carbs": 20},
    {"name": "Пшенная каша", "calories": 90, "proteins": 3.0, "fats": 1.0, "carbs": 17},
    {"name": "Картофельное пюре", "calories": 106, "proteins": 2.0, "fats": 4.0, "carbs": 16},
    {"name": "Макароны по-флотски", "calories": 180, "proteins": 7.0, "fats": 5.0, "carbs": 28},
    {"name": "Жаркое", "calories": 150, "proteins": 12, "fats": 8.0, "carbs": 10},
    {"name": "Гуляш", "calories": 120, "proteins": 10, "fats": 6.0, "carbs": 5.0},
    {"name": "Бефстроганов", "calories": 145, "proteins": 12, "fats": 8.0, "carbs": 5.0},
    {"name": "Куриная лапша", "calories": 60, "proteins": 5.0, "fats": 2.0, "carbs": 6.0},
    {"name": "Фасоль стручковая тушеная", "calories": 35, "proteins": 2.0, "fats": 0.5, "carbs": 7.0},
    {"name": "Капуста тушеная", "calories": 50, "proteins": 2.0, "fats": 3.0, "carbs": 5.0},
    {"name": "Грибы жареные", "calories": 50, "proteins": 3.0, "fats": 3.0, "carbs": 3.0},
    {"name": "Овощи гриль", "calories": 60, "proteins": 2.0, "fats": 3.0, "carbs": 8.0},
    {"name": "Роллы Калифорния", "calories": 176, "proteins": 6.0, "fats": 5.0, "carbs": 28},
    {"name": "Суши с лососем", "calories": 120, "proteins": 6.0, "fats": 2.0, "carbs": 20},
    {"name": "Паста Карбонара", "calories": 400, "proteins": 15, "fats": 20, "carbs": 40},
    {"name": "Ризотто", "calories": 350, "proteins": 8.0, "fats": 12, "carbs": 50},
    {"name": "Фондю", "calories": 320, "proteins": 15, "fats": 20, "carbs": 15},
    {"name": "Курица табака", "calories": 210, "proteins": 25, "fats": 12, "carbs": 0},
    {"name": "Шашлык из свинины", "calories": 320, "proteins": 20, "fats": 25, "carbs": 0},
    {"name": "Люля-кебаб", "calories": 280, "proteins": 20, "fats": 20, "carbs": 5.0},
    {"name": "Котлета по-киевски", "calories": 350, "proteins": 20, "fats": 25, "carbs": 10},

    # Соусы и приправы 
    {"name": "Майонез Провансаль", "calories": 680, "proteins": 1.0, "fats": 70, "carbs": 3.0},
    {"name": "Кетчуп", "calories": 110, "proteins": 2.0, "fats": 0, "carbs": 25},
    {"name": "Горчица", "calories": 66, "proteins": 4.4, "fats": 3.7, "carbs": 5.0},
    {"name": "Соевый соус", "calories": 53, "proteins": 6.0, "fats": 0, "carbs": 5.0},
    {"name": "Аджика", "calories": 50, "proteins": 2.0, "fats": 0, "carbs": 10},
    {"name": "Хрен", "calories": 56, "proteins": 2.0, "fats": 0.5, "carbs": 12},
    {"name": "Тартар", "calories": 350, "proteins": 2.0, "fats": 35, "carbs": 5.0},
    {"name": "Барбекю соус", "calories": 120, "proteins": 1.0, "fats": 0, "carbs": 28},
    {"name": "Чесночный соус", "calories": 300, "proteins": 3.0, "fats": 30, "carbs": 5.0},
    {"name": "Сырный соус", "calories": 320, "proteins": 10, "fats": 25, "carbs": 15},
    {"name": "Ткемали", "calories": 50, "proteins": 1.0, "fats": 0, "carbs": 12},
    {"name": "Ореховый соус", "calories": 400, "proteins": 10, "fats": 35, "carbs": 15},
    {"name": "Бальзамический уксус", "calories": 88, "proteins": 0.5, "fats": 0, "carbs": 17},
    {"name": "Оливковое масло", "calories": 884, "proteins": 0, "fats": 100, "carbs": 0},
    {"name": "Подсолнечное масло", "calories": 884, "proteins": 0, "fats": 100, "carbs": 0},
    {"name": "Сливочное масло", "calories": 748, "proteins": 0.5, "fats": 82.5, "carbs": 0.8},
    {"name": "Маргарин", "calories": 717, "proteins": 0.3, "fats": 80, "carbs": 0.7},
    {"name": "Соль", "calories": 0, "proteins": 0, "fats": 0, "carbs": 0},
    {"name": "Сахар", "calories": 387, "proteins": 0, "fats": 0, "carbs": 100},
    {"name": "Мед", "calories": 329, "proteins": 0.8, "fats": 0, "carbs": 81},

    # Детское питание
    {"name": "Пюре яблочное", "calories": 50, "proteins": 0.3, "fats": 0.2, "carbs": 12},
    {"name": "Пюре грушевое", "calories": 45, "proteins": 0.4, "fats": 0.1, "carbs": 11},
    {"name": "Пюре тыквенное", "calories": 40, "proteins": 1.0, "fats": 0.1, "carbs": 9.0},
    {"name": "Пюре мясное", "calories": 80, "proteins": 10, "fats": 4.0, "carbs": 2.0},
    {"name": "Каша молочная", "calories": 120, "proteins": 3.0, "fats": 3.0, "carbs": 20},
    {"name": "Смесь молочная", "calories": 500, "proteins": 10, "fats": 25, "carbs": 60},
    {"name": "Пюре овощное", "calories": 60, "proteins": 2.0, "fats": 1.0, "carbs": 10},
    {"name": "Сок детский", "calories": 45, "proteins": 0.5, "fats": 0, "carbs": 11},
    {"name": "Печенье детское", "calories": 400, "proteins": 8.0, "fats": 10, "carbs": 70},

    # Диетические и специализированные продукты 
    {"name": "Протеиновый батончик", "calories": 250, "proteins": 20, "fats": 8.0, "carbs": 25},
    {"name": "Протеиновый коктейль", "calories": 120, "proteins": 25, "fats": 2.0, "carbs": 5.0},
    {"name": "Гейнер", "calories": 400, "proteins": 20, "fats": 5.0, "carbs": 70},
    {"name": "Аминокислоты BCAA", "calories": 0, "proteins": 100, "fats": 0, "carbs": 0},
    {"name": "Креатин", "calories": 0, "proteins": 0, "fats": 0, "carbs": 0},
    {"name": "L-карнитин", "calories": 0, "proteins": 0, "fats": 0, "carbs": 0},
    {"name": "Овсяные отруби", "calories": 246, "proteins": 17, "fats": 7.0, "carbs": 66},
    {"name": "Пшеничные отруби", "calories": 216, "proteins": 15, "fats": 4.0, "carbs": 64},
    {"name": "Семена чиа", "calories": 486, "proteins": 16, "fats": 31, "carbs": 42},
    {"name": "Семена льна", "calories": 534, "proteins": 18, "fats": 42, "carbs": 29},
    {"name": "Спирулина", "calories": 290, "proteins": 57, "fats": 8.0, "carbs": 24},
    {"name": "Хлорелла", "calories": 300, "proteins": 60, "fats": 10, "carbs": 20},
    {"name": "Тыквенные семечки", "calories": 559, "proteins": 30, "fats": 49, "carbs": 11},
    {"name": "Подсолнечные семечки", "calories": 584, "proteins": 21, "fats": 51, "carbs": 20},
    {"name": "Кунжут", "calories": 573, "proteins": 18, "fats": 50, "carbs": 23},
    {"name": "Миндальная мука", "calories": 600, "proteins": 22, "fats": 50, "carbs": 20},
    {"name": "Кокосовая мука", "calories": 400, "proteins": 15, "fats": 15, "carbs": 60},
    {"name": "Агар-агар", "calories": 300, "proteins": 0, "fats": 0, "carbs": 80},
    {"name": "Стевия", "calories": 0, "proteins": 0, "fats": 0, "carbs": 0},
    {"name": "Сироп топинамбура", "calories": 267, "proteins": 0, "fats": 0, "carbs": 70},

    # Замороженные продукты 
    {"name": "Овощная смесь", "calories": 50, "proteins": 2.0, "fats": 0.5, "carbs": 10},
    {"name": "Шпинат замороженный", "calories": 23, "proteins": 2.9, "fats": 0.4, "carbs": 3.6},
    {"name": "Брокколи замороженная", "calories": 34, "proteins": 2.8, "fats": 0.4, "carbs": 7},
    {"name": "Цветная капуста замороженная", "calories": 25, "proteins": 2.0, "fats": 0.3, "carbs": 5.0},
    {"name": "Стручковая фасоль замороженная", "calories": 35, "proteins": 2.0, "fats": 0.5, "carbs": 7.0},
    {"name": "Ягоды замороженные", "calories": 50, "proteins": 1.0, "fats": 0.5, "carbs": 12},
    {"name": "Фрукты замороженные", "calories": 60, "proteins": 1.0, "fats": 0.5, "carbs": 15},
    {"name": "Пельмени замороженные", "calories": 275, "proteins": 12, "fats": 15, "carbs": 25},
    {"name": "Блинчики замороженные", "calories": 233, "proteins": 6.1, "fats": 5.8, "carbs": 40},
    {"name": "Пицца замороженная", "calories": 209, "proteins": 8.0, "fats": 6.0, "carbs": 30},
    {"name": "Котлеты замороженные", "calories": 267, "proteins": 18, "fats": 20, "carbs": 4.0},
    {"name": "Рыба замороженная", "calories": 140, "proteins": 20, "fats": 6, "carbs": 0},
    {"name": "Креветки замороженные", "calories": 95, "proteins": 19, "fats": 1.1, "carbs": 1.0},
    {"name": "Мидии замороженные", "calories": 77, "proteins": 16, "fats": 1.1, "carbs": 0},
    {"name": "Кальмар замороженный", "calories": 100, "proteins": 18, "fats": 2.2, "carbs": 2.0},
    {"name": "Овощные котлеты замороженные", "calories": 150, "proteins": 5.0, "fats": 8.0, "carbs": 15},
    {"name": "Фруктовый лед", "calories": 100, "proteins": 0, "fats": 0, "carbs": 25},
    {"name": "Мороженое пломбир", "calories": 232, "proteins": 3.7, "fats": 15, "carbs": 20},
    {"name": "Мороженое эскимо", "calories": 250, "proteins": 4.0, "fats": 15, "carbs": 25},
    {"name": "Мороженое фруктовое", "calories": 150, "proteins": 2.0, "fats": 5.0, "carbs": 25},

    # Консервы 
    {"name": "Горошек зеленый консервированный", "calories": 81, "proteins": 5.4, "fats": 0.4, "carbs": 14},
    {"name": "Кукуруза консервированная", "calories": 120, "proteins": 3.0, "fats": 1.5, "carbs": 25},
    {"name": "Фасоль консервированная", "calories": 120, "proteins": 7.0, "fats": 0.5, "carbs": 22},
    {"name": "Оливки консервированные", "calories": 115, "proteins": 0.8, "fats": 11, "carbs": 6.0},
    {"name": "Маслины консервированные", "calories": 115, "proteins": 0.8, "fats": 11, "carbs": 6.0},
    {"name": "Шпроты в масле", "calories": 363, "proteins": 17, "fats": 32, "carbs": 0},
    {"name": "Сардины в масле", "calories": 221, "proteins": 24, "fats": 13, "carbs": 0},
    {"name": "Тунец в собственном соку", "calories": 96, "proteins": 21, "fats": 1.0, "carbs": 0},
    {"name": "Тунец в масле", "calories": 198, "proteins": 29, "fats": 8.0, "carbs": 0},
    {"name": "Сайра консервированная", "calories": 283, "proteins": 18, "fats": 23, "carbs": 0},
    {"name": "Икра баклажанная", "calories": 148, "proteins": 1.7, "fats": 13, "carbs": 5.0},
    {"name": "Икра кабачковая", "calories": 122, "proteins": 1.5, "fats": 9.0, "carbs": 8.0},
    {"name": "Лечо", "calories": 50, "proteins": 1.0, "fats": 2.0, "carbs": 7.0},
    {"name": "Томатная паста", "calories": 82, "proteins": 4.3, "fats": 0.5, "carbs": 19},
    {"name": "Ананасы консервированные", "calories": 60, "proteins": 0.5, "fats": 0.2, "carbs": 15},
    {"name": "Персики консервированные", "calories": 50, "proteins": 0.5, "fats": 0.1, "carbs": 13},
    {"name": "Грибы консервированные", "calories": 25, "proteins": 3.0, "fats": 1.0, "carbs": 2.0},
    {"name": "Огурцы консервированные", "calories": 16, "proteins": 0.7, "fats": 0.1, "carbs": 3.6},
    {"name": "Помидоры консервированные", "calories": 18, "proteins": 0.9, "fats": 0.2, "carbs": 3.9},
    {"name": "Сгущенное молоко", "calories": 328, "proteins": 7.2, "fats": 8.5, "carbs": 56},

    # Орехи и сухофрукты 
    {"name": "Грецкий орех", "calories": 654, "proteins": 15, "fats": 65, "carbs": 14},
    {"name": "Миндаль", "calories": 609, "proteins": 19, "fats": 54, "carbs": 13},
    {"name": "Фундук", "calories": 628, "proteins": 15, "fats": 61, "carbs": 17},
    {"name": "Кешью", "calories": 600, "proteins": 18, "fats": 48, "carbs": 22},
    {"name": "Фисташки", "calories": 562, "proteins": 20, "fats": 45, "carbs": 27},
    {"name": "Арахис", "calories": 567, "proteins": 26, "fats": 49, "carbs": 16},
    {"name": "Кедровые орехи", "calories": 673, "proteins": 14, "fats": 68, "carbs": 13},
    {"name": "Бразильский орех", "calories": 659, "proteins": 14, "fats": 67, "carbs": 12},
    {"name": "Пекан", "calories": 691, "proteins": 9.0, "fats": 72, "carbs": 14},
    {"name": "Курага", "calories": 241, "proteins": 3.4, "fats": 0.5, "carbs": 63},
    {"name": "Чернослив", "calories": 240, "proteins": 2.2, "fats": 0.4, "carbs": 64},
    {"name": "Изюм", "calories": 299, "proteins": 3.1, "fats": 0.5, "carbs": 79},
    {"name": "Финики", "calories": 282, "proteins": 2.5, "fats": 0.4, "carbs": 75},
    {"name": "Инжир сушеный", "calories": 249, "proteins": 3.3, "fats": 0.9, "carbs": 64},
    {"name": "Яблоки сушеные", "calories": 243, "proteins": 2.2, "fats": 0.3, "carbs": 66},
    {"name": "Груши сушеные", "calories": 249, "proteins": 2.3, "fats": 0.6, "carbs": 63},
    {"name": "Вишня сушеная", "calories": 290, "proteins": 1.5, "fats": 0.3, "carbs": 73},
    {"name": "Клюква сушеная", "calories": 308, "proteins": 0.1, "fats": 1.4, "carbs": 82},
    {"name": "Бананы сушеные", "calories": 346, "proteins": 3.9, "fats": 1.8, "carbs": 88},
    {"name": "Ананас сушеный", "calories": 268, "proteins": 1.0, "fats": 1.3, "carbs": 70},

    # Масла и жиры 
    {"name": "Кокосовое масло", "calories": 862, "proteins": 0, "fats": 100, "carbs": 0},
    {"name": "Льняное масло", "calories": 884, "proteins": 0, "fats": 100, "carbs": 0},
    {"name": "Кунжутное масло", "calories": 884, "proteins": 0, "fats": 100, "carbs": 0},
    {"name": "Масло виноградной косточки", "calories": 884, "proteins": 0, "fats": 100, "carbs": 0},
    {"name": "Гхи", "calories": 900, "proteins": 0, "fats": 100, "carbs": 0},
    {"name": "Сало", "calories": 902, "proteins": 2.4, "fats": 99, "carbs": 0},
    {"name": "Рыбий жир", "calories": 902, "proteins": 0, "fats": 100, "carbs": 0},
    {"name": "Смалец", "calories": 900, "proteins": 0, "fats": 100, "carbs": 0},
    {"name": "Масло авокадо", "calories": 884, "proteins": 0, "fats": 100, "carbs": 0},

    # Специи и пряности (20)
    {"name": "Корица", "calories": 247, "proteins": 4.0, "fats": 1.2, "carbs": 81},
    {"name": "Куркума", "calories": 312, "proteins": 9.7, "fats": 3.2, "carbs": 65},
    {"name": "Имбирь молотый", "calories": 335, "proteins": 9.0, "fats": 4.2, "carbs": 72},
    {"name": "Карри", "calories": 325, "proteins": 12, "fats": 14, "carbs": 58},
    {"name": "Паприка", "calories": 282, "proteins": 14, "fats": 13, "carbs": 54},
    {"name": "Кориандр", "calories": 298, "proteins": 12, "fats": 18, "carbs": 55},
    {"name": "Тмин", "calories": 333, "proteins": 20, "fats": 15, "carbs": 50},
    {"name": "Гвоздика", "calories": 274, "proteins": 6.0, "fats": 13, "carbs": 66},
    {"name": "Мускатный орех", "calories": 525, "proteins": 6.0, "fats": 36, "carbs": 49},
    {"name": "Кардамон", "calories": 311, "proteins": 11, "fats": 7.0, "carbs": 68},
    {"name": "Базилик сушеный", "calories": 233, "proteins": 23, "fats": 4.0, "carbs": 47},
    {"name": "Орегано", "calories": 265, "proteins": 9.0, "fats": 4.3, "carbs": 69},
    {"name": "Розмарин", "calories": 331, "proteins": 4.9, "fats": 15, "carbs": 64},
    {"name": "Тимьян", "calories": 276, "proteins": 9.1, "fats": 7.4, "carbs": 63},
    {"name": "Мята", "calories": 70, "proteins": 3.8, "fats": 0.9, "carbs": 15},
    {"name": "Лавровый лист", "calories": 313, "proteins": 8.0, "fats": 8.4, "carbs": 75},
    {"name": "Шафран", "calories": 310, "proteins": 11, "fats": 6.0, "carbs": 65},
    {"name": "Ваниль", "calories": 288, "proteins": 0.1, "fats": 0.1, "carbs": 13},
    {"name": "Горчица зерновая", "calories": 508, "proteins": 26, "fats": 36, "carbs": 28},
    {"name": "Хмели-сунели", "calories": 250, "proteins": 10, "fats": 5.0, "carbs": 50},

    # Фастфуд 
    {"name": "Картофель фри", "calories": 312, "proteins": 3.4, "fats": 15, "carbs": 41},
    {"name": "Чизбургер", "calories": 303, "proteins": 15, "fats": 13, "carbs": 30},
    {"name": "Биг Мак", "calories": 563, "proteins": 25, "fats": 33, "carbs": 44},
    {"name": "Наггетсы куриные", "calories": 296, "proteins": 15, "fats": 18, "carbs": 19},
    {"name": "Пицца пепперони", "calories": 280, "proteins": 12, "fats": 10, "carbs": 35},
    {"name": "Хот-дог", "calories": 290, "proteins": 10, "fats": 15, "carbs": 28},
    {"name": "Буррито", "calories": 350, "proteins": 15, "fats": 12, "carbs": 45},
    {"name": "Куриные крылышки", "calories": 320, "proteins": 20, "fats": 25, "carbs": 5.0},
    {"name": "Лаваш с курицей", "calories": 350, "proteins": 20, "fats": 15, "carbs": 30},
    {"name": "Сэндвич с ветчиной", "calories": 250, "proteins": 14, "fats": 8.0, "carbs": 30},

    # Алкогольные напитки 
    {"name": "Пиво светлое", "calories": 42, "proteins": 0.5, "fats": 0, "carbs": 3.5},
    {"name": "Пиво темное", "calories": 48, "proteins": 0.6, "fats": 0, "carbs": 5.0},
    {"name": "Вино красное сухое", "calories": 68, "proteins": 0.2, "fats": 0, "carbs": 2.6},
    {"name": "Вино белое сухое", "calories": 66, "proteins": 0.1, "fats": 0, "carbs": 2.6},
    {"name": "Шампанское", "calories": 85, "proteins": 0.2, "fats": 0, "carbs": 5.0},
    {"name": "Водка", "calories": 235, "proteins": 0, "fats": 0, "carbs": 0},
    {"name": "Виски", "calories": 250, "proteins": 0, "fats": 0, "carbs": 0},
    {"name": "Коньяк", "calories": 239, "proteins": 0, "fats": 0, "carbs": 1.5},
    {"name": "Ром", "calories": 231, "proteins": 0, "fats": 0, "carbs": 0},
    {"name": "Текила", "calories": 231, "proteins": 0, "fats": 0, "carbs": 0},

    # Добавки и подсластители 
    {"name": "Аспартам", "calories": 0, "proteins": 0, "fats": 0, "carbs": 0},
    {"name": "Сорбит", "calories": 260, "proteins": 0, "fats": 0, "carbs": 65},
    {"name": "Ксилит", "calories": 240, "proteins": 0, "fats": 0, "carbs": 60},
    {"name": "Фруктоза", "calories": 400, "proteins": 0, "fats": 0, "carbs": 100},
    {"name": "Сахароза", "calories": 387, "proteins": 0, "fats": 0, "carbs": 100},
    {"name": "Мальтодекстрин", "calories": 380, "proteins": 0, "fats": 0, "carbs": 95},
    {"name": "Сироп агавы", "calories": 310, "proteins": 0, "fats": 0, "carbs": 76},
    {"name": "Кленовый сироп", "calories": 260, "proteins": 0, "fats": 0, "carbs": 67},
    {"name": "Патока", "calories": 300, "proteins": 0, "fats": 0, "carbs": 75},

    # Другие продукты 
    {"name": "Желатин", "calories": 335, "proteins": 85, "fats": 0, "carbs": 0},
    {"name": "Дрожжи сухие", "calories": 325, "proteins": 40, "fats": 7.0, "carbs": 41},
    {"name": "Разрыхлитель", "calories": 53, "proteins": 0, "fats": 0, "carbs": 13},
    {"name": "Сода пищевая", "calories": 0, "proteins": 0, "fats": 0, "carbs": 0},
    {"name": "Уксус столовый", "calories": 18, "proteins": 0, "fats": 0, "carbs": 5.0},
]